demo:
	gcc -Wall -std=c99 demo.c t1.c -o demo
demo1:
	gcc -Wall -std=c99 demo.c t2.c -o demo1
all:
	gcc -Wall -std=c99 demo.c t1.c -o demo 
	gcc -Wall -std=c99 demo.c t2.c -o demo1
clean:
	rm demo 
	rm demo1